const canvas = document.getElementById('gameCanvas');
const ctx = canvas.getContext('2d');
const htmlGame = document.getElementById('htmlGame');
const scoreEl = document.getElementById('score'), statusEl = document.getElementById('status'), timeEl = document.getElementById('time'), titleEl = document.getElementById('gameTitle'), helpEl = document.getElementById('gameHelp'), globalHighEl = document.getElementById('globalHigh');
const startBtn = document.getElementById('startBtn'), resetBtn = document.getElementById('resetBtn');
let current = 'snake', score = 0, running = false, loopId = null, seconds = 0, timer = null, key = '', pointerDir = '';
const highKey = 'retro-hub-high-score';
globalHighEl.textContent = localStorage.getItem(highKey) || 0;
const info = {
  snake:['Snake','Dùng phím mũi tên hoặc WASD để điều khiển rắn.'],
  pong:['Pong','Di chuyển thanh đỡ bằng chuột hoặc phím W/S.'],
  breakout:['Breakout','Di chuyển thanh đỡ bằng chuột hoặc phím A/D để phá gạch.'],
  memory:['Memory Card','Lật 2 thẻ giống nhau để ghi điểm.'],
  clicker:['Click Speed','Bấm thật nhanh trong 10 giây để đo tốc độ.']
};
function setScore(v){score=v;scoreEl.textContent=v;const h=Number(localStorage.getItem(highKey)||0);if(v>h){localStorage.setItem(highKey,v);globalHighEl.textContent=v}}
function status(v){statusEl.textContent=v}
function startTimer(){clearInterval(timer);seconds=0;timeEl.textContent='00:00';timer=setInterval(()=>{seconds++;timeEl.textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0')},1000)}
function stopAll(){running=false;clearInterval(loopId);clearInterval(timer);loopId=null;timer=null}
function clear(){ctx.fillStyle='#05050d';ctx.fillRect(0,0,canvas.width,canvas.height)}
document.querySelectorAll('.game-btn').forEach(b=>b.onclick=()=>{document.querySelector('.active').classList.remove('active');b.classList.add('active');current=b.dataset.game;titleEl.textContent=info[current][0];helpEl.textContent=info[current][1];resetGame()});
startBtn.onclick=()=>startGame();resetBtn.onclick=()=>resetGame();
document.addEventListener('keydown',e=>{key=e.key.toLowerCase()});
canvas.addEventListener('mousemove',e=>{canvas.mouseX=(e.offsetX/canvas.clientWidth)*canvas.width;canvas.mouseY=(e.offsetY/canvas.clientHeight)*canvas.height});
document.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>pointerDir=b.dataset.dir);
function startGame(){stopAll();setScore(0);status('Playing');startTimer();canvas.classList.remove('hidden');htmlGame.classList.add('hidden');if(current==='snake') snake();if(current==='pong') pong();if(current==='breakout') breakout();if(current==='memory') memory();if(current==='clicker') clicker()}
function resetGame(){stopAll();setScore(0);status('Ready');timeEl.textContent='00:00';htmlGame.innerHTML='';canvas.classList.remove('hidden');htmlGame.classList.add('hidden');clear();ctx.fillStyle='#2affd5';ctx.font='30px Consolas';ctx.textAlign='center';ctx.fillText('Press START',canvas.width/2,canvas.height/2)}
function snake(){let grid=20, snake=[{x:160,y:160}], food={x:320,y:200}, dx=grid,dy=0;running=true;loopId=setInterval(()=>{if(['arrowup','w'].includes(key)||pointerDir==='up'){dx=0;dy=-grid}if(['arrowdown','s'].includes(key)||pointerDir==='down'){dx=0;dy=grid}if(['arrowleft','a'].includes(key)||pointerDir==='left'){dx=-grid;dy=0}if(['arrowright','d'].includes(key)||pointerDir==='right'){dx=grid;dy=0}pointerDir='';let head={x:snake[0].x+dx,y:snake[0].y+dy};if(head.x<0||head.y<0||head.x>=canvas.width||head.y>=canvas.height||snake.some(p=>p.x===head.x&&p.y===head.y)){stopAll();status('Game Over');return}snake.unshift(head);if(head.x===food.x&&head.y===food.y){setScore(score+10);food={x:Math.floor(Math.random()*36)*grid,y:Math.floor(Math.random()*21)*grid}}else snake.pop();clear();ctx.fillStyle='#ff3df2';ctx.fillRect(food.x,food.y,grid-2,grid-2);ctx.fillStyle='#2affd5';snake.forEach(p=>ctx.fillRect(p.x,p.y,grid-2,grid-2))},110)}
function pong(){let p={x:20,y:160,w:15,h:90}, ai={x:685,y:160,w:15,h:90}, ball={x:360,y:210,vx:5,vy:4,r:9};running=true;loopId=setInterval(()=>{if(['w','arrowup'].includes(key))p.y-=12;if(['s','arrowdown'].includes(key))p.y+=12;if(canvas.mouseY)p.y=canvas.mouseY-p.h/2;p.y=Math.max(0,Math.min(canvas.height-p.h,p.y));ai.y+=(ball.y-ai.y-ai.h/2)*.08;ball.x+=ball.vx;ball.y+=ball.vy;if(ball.y<ball.r||ball.y>canvas.height-ball.r)ball.vy*=-1;[p,ai].forEach(r=>{if(ball.x>r.x&&ball.x<r.x+r.w&&ball.y>r.y&&ball.y<r.y+r.h){ball.vx*=-1.08;setScore(score+1)}});if(ball.x<0||ball.x>canvas.width){stopAll();status(ball.x<0?'You Lost':'You Win');return}clear();ctx.fillStyle='#2affd5';ctx.fillRect(p.x,p.y,p.w,p.h);ctx.fillStyle='#ff3df2';ctx.fillRect(ai.x,ai.y,ai.w,ai.h);ctx.fillStyle='#ffe66d';ctx.beginPath();ctx.arc(ball.x,ball.y,ball.r,0,Math.PI*2);ctx.fill()},16)}
function breakout(){let paddle={x:300,y:390,w:110,h:14}, ball={x:360,y:360,vx:4,vy:-5,r:8}, bricks=[];for(let r=0;r<5;r++)for(let c=0;c<10;c++)bricks.push({x:35+c*66,y:35+r*28,w:56,h:18,on:true});loopId=setInterval(()=>{if(['a','arrowleft'].includes(key))paddle.x-=11;if(['d','arrowright'].includes(key))paddle.x+=11;if(canvas.mouseX)paddle.x=canvas.mouseX-paddle.w/2;paddle.x=Math.max(0,Math.min(canvas.width-paddle.w,paddle.x));ball.x+=ball.vx;ball.y+=ball.vy;if(ball.x<ball.r||ball.x>canvas.width-ball.r)ball.vx*=-1;if(ball.y<ball.r)ball.vy*=-1;if(ball.y>canvas.height){stopAll();status('Game Over');return}if(ball.x>paddle.x&&ball.x<paddle.x+paddle.w&&ball.y>paddle.y&&ball.y<paddle.y+paddle.h)ball.vy=-Math.abs(ball.vy);bricks.forEach(b=>{if(b.on&&ball.x>b.x&&ball.x<b.x+b.w&&ball.y>b.y&&ball.y<b.y+b.h){b.on=false;ball.vy*=-1;setScore(score+5)}});if(bricks.every(b=>!b.on)){stopAll();status('You Win')}clear();ctx.fillStyle='#2affd5';ctx.fillRect(paddle.x,paddle.y,paddle.w,paddle.h);ctx.fillStyle='#ffe66d';ctx.beginPath();ctx.arc(ball.x,ball.y,ball.r,0,7);ctx.fill();ctx.fillStyle='#ff3df2';bricks.filter(b=>b.on).forEach(b=>ctx.fillRect(b.x,b.y,b.w,b.h))},16)}
function memory(){canvas.classList.add('hidden');htmlGame.classList.remove('hidden');let icons=['🍒','🍋','🍇','🍉','⭐','🚀','🎮','👾'];let deck=[...icons,...icons].sort(()=>Math.random()-.5);let first=null, lock=false;htmlGame.innerHTML='<div class="memory-grid">'+deck.map((_,i)=>`<div class="card" data-i="${i}">?</div>`).join('')+'</div>';htmlGame.querySelectorAll('.card').forEach(card=>card.onclick=()=>{if(lock||card.classList.contains('done')||card===first)return;let i=card.dataset.i;card.textContent=deck[i];card.classList.add('open');if(!first){first=card}else{lock=true;setTimeout(()=>{if(deck[first.dataset.i]===deck[i]){first.classList.add('done');card.classList.add('done');setScore(score+10);if(htmlGame.querySelectorAll('.done').length===16){stopAll();status('You Win')}}else{first.textContent='?';card.textContent='?';first.classList.remove('open');card.classList.remove('open')}first=null;lock=false},650)}})}
function clicker(){canvas.classList.add('hidden');htmlGame.classList.remove('hidden');let left=10, clicks=0;htmlGame.innerHTML='<div class="click-zone">Click để bắt đầu!</div>';let zone=htmlGame.querySelector('.click-zone'), started=false, t;zone.onclick=()=>{if(!started){started=true;status('Playing');t=setInterval(()=>{left--;zone.innerHTML=`Click nhanh!<br>${left}s<br>${clicks} clicks`;if(left<=0){clearInterval(t);stopAll();status('Finished');zone.innerHTML=`Kết quả: ${clicks} clicks<br>Tốc độ: ${(clicks/10).toFixed(1)} click/s`}},1000)}clicks++;setScore(clicks);zone.innerHTML=`Click nhanh!<br>${left}s<br>${clicks} clicks`}}
resetGame();
