create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  task text not null,
  is_complete boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.todos enable row level security;

create policy "Todos are readable by everyone"
on public.todos
for select
to anon, authenticated
using (true);

create policy "Todos can be inserted by everyone"
on public.todos
for insert
to anon, authenticated
with check (true);
